# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
# IP: The module: 'design_1_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
# IP: The module: 'design_1_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
