@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1_AR70908 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Aug 06 21:54:32 +1000 2018
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
call xelab  -wto 32ba1800294b4335a059dc7c1c7eb1ce --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot aes_encryption_wrapper_tb_behav xil_defaultlib.aes_encryption_wrapper_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
