set_property SRC_FILE_INFO {cfile:D:/git_repos/aes_encryption_vhdl_implementation/vivado_project/pynq_testing/pynq_testing.srcs/constrs_1/new/pynq_aes_encryption_constraints.xdc rfile:../../../pynq_testing.srcs/constrs_1/new/pynq_aes_encryption_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports o_valid]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports reset]
